version: '2'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 33060:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: db
  mongo:
    image: mongo:4.0-xenial
    ports:
      - 27016:27017
